### ISSUE TITLE
setDeviceMetricsOverride() got an unexpected keyword argument 'fitWindow'

### ISSUE THREAD

**Issue by primoz-k** [chuckus/chromewhip#4]
So, I started playing with chromewhip and I have it running with Docker (with the command from the README):

    2017-09-11 10:07:50,411 chromewhip.chrome.ChromeTab                                      INFO     Connected to Chrome tab ws://127.0.0.1:9222/devtools/page/81b27929-4426-4586-b06d-22c0b063d26f
    2017-09-11 10:07:50,412 chromewhip.chrome.Chrome                                         DEBUG    Connected to Chrome! Found 1 tabs
    2017-09-11 10:07:50,412 chromewhip.chrome.ChromeTab.recv_handler                         DEBUG    
    Waiting for message...
    ======== Running on http://0.0.0.0 ========
    (Press CTRL+C to quit)
    
And I make a request, let's say:

    curl "http://0.0.0.0:8080/render.html?url=http://www.google.com"

This is the response:

    {
        "error": "Traceback (most recent call last):
        File \"/usr/src/app/chromewhip/middleware.py\", line 20, in middleware_handler
        response = await handler(request)
        File \"/usr/src/app/chromewhip/views.py\", line 60, in render_html
        tab = await _go(request)
        File \"/usr/src/app/chromewhip/views.py\", line 45, in _go
        fitWindow=False)
        TypeError: setDeviceMetricsOverride() got an unexpected keyword argument 'fitWindow'"
    }

Am I doing something wrong?

**Comment by chuckus** [comment]
Thanks for raising, looking into it now.

**Comment by chuckus** [comment]
Please try with latest docker image from Dockerhub. Just updated and regenerated the devtools protocol files - I really should automate that process... let me know how you go.

**Comment by primoz-k** [comment]
Perfect! It works! Thank you.
